name: Wake Streamlit App

on:
  schedule:
    - cron: "0 */12 * * *"   # cada 12 horas
  workflow_dispatch:        # permite correrlo a mano

jobs:
  wake:
    runs-on: ubuntu-latest
    steps:
      - name: Wake Streamlit
        run: |
          echo "Waking Streamlit app..."
          curl -L -s https://mercadopago-donelio.streamlit.app/ > /dev/null
          echo "Done"
